import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "../styles/globals.css";
import TanStackQueryProvider from "@/provider/TanstacQueryProvide";
import { AuthProvider } from "@/context/AuthContext";

// const inter = Inter({ subsets: ["latin"] });
const urbanist = Urbanist({ subsets: ["latin"] }); // Import Urbanist font

export const metadata: Metadata = {
  title: "Cricketangon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <AuthProvider>
          <TanStackQueryProvider>{children}</TanStackQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
